// Encyclopedia data — edit freely to add, remove, or rewrite entries.
// Each entry: term (display name), cat (category key, see CATEGORIES below),
// def (definition/notes), and optional img (path to a reference image).

window.CATEGORIES = [
  { key: "mega", label: "Megastructures & Habitats" },
  { key: "style", label: "Architecture Styles & Movements" },
  { key: "architect", label: "Architects & Designers" },
  { key: "building", label: "Buildings & Spaces" },
  { key: "material", label: "Materials & Details" },
  { key: "vehicle", label: "Vehicles & Craft" },
  { key: "tech", label: "Technology & Systems" },
  { key: "industry", label: "Industry & Infrastructure" },
  { key: "environment", label: "Environments & Terrain" },
  { key: "creature", label: "Creatures & Paleontology" },
  { key: "scene", label: "Scene Prompts & Descriptors" },
];

window.TERMS = [
  {"term": "Air/Water Treatment Plant", "slug": "air-water-treatment-plant", "cat": "industry", "def": "A facility that processes air or water to make it safe or usable — often a visually rich tangle of tanks, filtration units, and pipework.", "img": ""},
  {"term": "Alderson Disk", "slug": "alderson-disk", "cat": "mega", "def": "A hypothetical megastructure: a vast solid disk with a star at its center, offering enormously more habitable surface area than any planet.", "img": ""},
  {"term": "Alien Creature", "slug": "alien-creature", "cat": "creature", "def": "Any lifeform originating from beyond Earth.", "img": ""},
  {"term": "Alien Ecosystem", "slug": "alien-ecosystem", "cat": "environment", "def": "A self-sustaining web of non-Earth flora and fauna, and the environment that supports it.", "img": ""},
  {"term": "All Terrain Vehicle (ATV)", "slug": "all-terrain-vehicle-atv", "cat": "vehicle", "def": "A light, rugged vehicle engineered to traverse rough or unstructured terrain.", "img": ""},
  {"term": "Ancient", "slug": "ancient", "cat": "scene", "def": "A descriptor marking a subject as extremely old — used to set the age and weathering of a structure or object.", "img": ""},
  {"term": "Antenna", "slug": "antenna", "cat": "tech", "def": "A structure designed to transmit or receive electromagnetic signals.", "img": ""},
  {"term": "Arclogy - Bounded Density", "slug": "arclogy-bounded-density", "cat": "style", "def": "An arcology variant defined by a hard edge — growth and density are contained within a fixed footprint rather than sprawling outward.", "img": ""},
  {"term": "Arcology", "slug": "arcology", "cat": "style", "def": "An architecture-and-ecology portmanteau coined by Paolo Soleri: a single, dense, self-sufficient megastructure meant to house an entire urban population on a minimal footprint.", "img": ""},
  {"term": "Arrival", "slug": "arrival", "cat": "scene", "def": "A compositional or narrative beat centered on a character or vehicle first reaching a place.", "img": ""},
  {"term": "Artificial Gravity", "slug": "artificial-gravity", "cat": "tech", "def": "Simulated gravity produced mechanically, typically by rotation, rather than by a planet's mass.", "img": ""},
  {"term": "Astrolabe", "slug": "astrolabe", "cat": "tech", "def": "A historical astronomical instrument used to measure the positions of celestial bodies and solve problems of time and location.", "img": ""},
  {"term": "Atmospheric Reclamation", "slug": "atmospheric-reclamation", "cat": "industry", "def": "The process of capturing and reprocessing a habitat's air supply to sustain a closed environment.", "img": ""},
  {"term": "Atrium", "slug": "atrium", "cat": "building", "def": "A large, often top-lit interior space rising through multiple floors of a building, drawing light and circulation into its center.", "img": ""},
  {"term": "Bastions", "slug": "bastions", "cat": "material", "def": "Projecting sections of a fortification designed to let defenders cover the wall's face with flanking fire.", "img": ""},
  {"term": "Bathhouse", "slug": "bathhouse", "cat": "building", "def": "A building dedicated to communal bathing — historically as much a social and civic space as a hygienic one.", "img": ""},
  {"term": "Bernal Sphere", "slug": "bernal-sphere", "cat": "mega", "def": "A proposed space habitat design: a hollow sphere about a mile across, spun for artificial gravity along its equator, with low-gravity zones near the poles.", "img": ""},
  {"term": "Bioclimatic Architecture", "slug": "bioclimatic-architecture", "cat": "style", "def": "A design approach that shapes a building's form, orientation, and materials around local sun, wind, and temperature to reduce mechanical heating and cooling.", "img": ""},
  {"term": "Birch Planet", "slug": "birch-planet", "cat": "mega", "def": "A theoretical megastructure that reshapes a star system's mass into nested shells of small, tightly-orbiting worlds around a dim star, maximizing habitable area from limited stellar output.", "img": ""},
  {"term": "Bishop Ring", "slug": "bishop-ring", "cat": "mega", "def": "A mid-scale spin habitat concept between a Stanford Torus and a full ringworld — a rotating ring roughly 1,000 km across, built from advanced materials rather than a single solid mass.", "img": ""},
  {"term": "Brain-Computer Interface", "slug": "brain-computer-interface", "cat": "tech", "def": "A direct communication link between a brain and an external device, bypassing the body's normal output pathways.", "img": ""},
  {"term": "Brutalist Base", "slug": "brutalist-base", "cat": "style", "def": "A structure built in the Brutalist idiom — raw exposed concrete, heavy massing, and unapologetic utility — recast as a base or outpost.", "img": ""},
  {"term": "Card Reader", "slug": "card-reader", "cat": "tech", "def": "A device that reads data from a card, commonly for identification or access control.", "img": ""},
  {"term": "Cargo Hauler", "slug": "cargo-hauler", "cat": "vehicle", "def": "A vehicle or craft designed primarily to move freight rather than passengers.", "img": ""},
  {"term": "Carlo Scarpa", "slug": "carlo-scarpa", "cat": "architect", "def": "Italian architect (1906–1978) known for meticulous detailing and layered materials, inserting modern interventions into historic fabric — Castelvecchio Museum, Brion Cemetery.", "img": ""},
  {"term": "Cartridge", "slug": "cartridge", "cat": "tech", "def": "A removable, self-contained module — of ammunition, data, or fuel — designed for quick insertion and swap.", "img": ""},
  {"term": "Catwalk", "slug": "catwalk", "cat": "material", "def": "A narrow raised walkway, typically structural or industrial, used for access, inspection, or performance.", "img": ""},
  {"term": "Citadel", "slug": "citadel", "cat": "building", "def": "A fortress positioned to command and defend a city — usually the strongest, most defensible point of a settlement.", "img": ""},
  {"term": "City in Gas Giant", "slug": "city-in-gas-giant", "cat": "mega", "def": "A floating settlement suspended within a gas giant's upper atmosphere, buoyant at the altitude where pressure and temperature are survivable.", "img": ""},
  {"term": "City integrated into Nature", "slug": "city-integrated-into-nature", "cat": "mega", "def": "An urban settlement whose plan, structure, and skin are designed to merge with — rather than clear — existing terrain and ecology.", "img": ""},
  {"term": "Cockpit", "slug": "cockpit", "cat": "vehicle", "def": "The compartment from which a vehicle or craft is piloted.", "img": ""},
  {"term": "Coelurosauria (SEE-lure-oh-SORE-ee-uh)", "slug": "coelurosauria-see-lure-oh-sore-ee-uh", "cat": "creature", "def": "A large group of theropod dinosaurs — including tyrannosaurs, birds, and their close relatives — characterized by a lightweight, often feathered build.", "img": ""},
  {"term": "Communications Satellite", "slug": "communications-satellite", "cat": "tech", "def": "A satellite that relays telecommunications signals between points on a planet's surface.", "img": ""},
  {"term": "Compsognathus", "slug": "compsognathus", "cat": "creature", "def": "A small, fast, chicken-sized theropod dinosaur from the late Jurassic period.", "img": ""},
  {"term": "Congeal", "slug": "congeal", "cat": "scene", "def": "A moment or surface where something — light, material, or a crowd — thickens and comes together into a solid mass.", "img": ""},
  {"term": "Controlled Spectacle", "slug": "controlled-spectacle", "cat": "scene", "def": "A dramatic display staged and managed for effect, rather than arising spontaneously.", "img": ""},
  {"term": "Convent", "slug": "convent", "cat": "building", "def": "A building or complex housing a religious community, typically organized around a cloister and shared devotional spaces.", "img": ""},
  {"term": "Corporate HQ", "slug": "corporate-hq", "cat": "building", "def": "A company's flagship building — architecture used deliberately as an expression of brand, scale, and authority.", "img": ""},
  {"term": "Corten", "slug": "corten", "cat": "material", "def": "Weathering steel (COR-TEN) that forms a stable, rust-like patina, prized for a warm, aged surface that needs no paint.", "img": ""},
  {"term": "Cove Lighting", "slug": "cove-lighting", "cat": "material", "def": "Concealed lighting recessed into a ledge or cove so the fixture is hidden and only its reflected glow is seen.", "img": ""},
  {"term": "Crash Site", "slug": "crash-site", "cat": "environment", "def": "The location where a vehicle or craft has come down in an uncontrolled or violent landing.", "img": ""},
  {"term": "Cretaceous Period", "slug": "cretaceous-period", "cat": "creature", "def": "The final period of the Mesozoic Era, roughly 145 to 66 million years ago, ending with the extinction of the non-avian dinosaurs.", "img": ""},
  {"term": "Crew Pod", "slug": "crew-pod", "cat": "vehicle", "def": "A small, often detachable module built to house a craft's crew.", "img": ""},
  {"term": "Cryonics", "slug": "cryonics", "cat": "tech", "def": "The practice of preserving a body at very low temperatures in the hope of future revival.", "img": ""},
  {"term": "Destratification Fan", "slug": "destratification-fan", "cat": "industry", "def": "A large fan used to mix stratified air layers within a big enclosed volume, evening out temperature top to bottom.", "img": ""},
  {"term": "Dieter Rams", "slug": "dieter-rams", "cat": "architect", "def": "German industrial designer, longtime head of design at Braun, known for his \"ten principles of good design\" and a restrained, functionalist aesthetic.", "img": ""},
  {"term": "Digital Projectors", "slug": "digital-projectors", "cat": "material", "def": "Projection units integrated into architecture to layer moving images, information, or advertising onto surfaces.", "img": ""},
  {"term": "Docking Port", "slug": "docking-port", "cat": "building", "def": "A fixture where a vehicle or vessel connects to a station or another craft to transfer people, cargo, or resources.", "img": ""},
  {"term": "Dropship", "slug": "dropship", "cat": "vehicle", "def": "A craft designed for rapid, often one-way descent from orbit or a larger vessel to deploy troops or cargo.", "img": ""},
  {"term": "Dyson Sphere", "slug": "dyson-sphere", "cat": "mega", "def": "A theoretical megastructure enclosing a star to capture the majority of its energy output, ranging from a solid shell to a swarm of orbiting collectors.", "img": ""},
  {"term": "Embassy", "slug": "embassy", "cat": "building", "def": "A diplomatic mission's building — legally an extension of a foreign nation's territory within a host city.", "img": ""},
  {"term": "Enclosure", "slug": "enclosure", "cat": "building", "def": "A bounded area set apart from its surroundings by a wall, fence, or structure.", "img": ""},
  {"term": "Entry Port", "slug": "entry-port", "cat": "building", "def": "A controlled point of arrival into a structure or settlement — the first threshold that sets scale and mood.", "img": ""},
  {"term": "Excavation", "slug": "excavation", "cat": "environment", "def": "A site or process of digging to expose or extract something buried.", "img": ""},
  {"term": "Exploring", "slug": "exploring", "cat": "scene", "def": "A compositional focus on a character or vehicle moving through and discovering an unfamiliar space.", "img": ""},
  {"term": "Exterior Structure", "slug": "exterior-structure", "cat": "building", "def": "A generic term for a building's outward-facing form and massing, as distinct from its interior.", "img": ""},
  {"term": "Facility", "slug": "facility", "cat": "building", "def": "A generic built structure equipped for a specific function — often a placeholder for industrial, research, or support architecture.", "img": ""},
  {"term": "Fall Protection", "slug": "fall-protection", "cat": "material", "def": "Guardrails, harness points, or netting engineered into a structure to prevent falls from height.", "img": ""},
  {"term": "Farm", "slug": "farm", "cat": "industry", "def": "Land or a facility dedicated to cultivating crops or raising livestock.", "img": ""},
  {"term": "Faster than Light Travel (FTL)", "slug": "faster-than-light-travel-ftl", "cat": "tech", "def": "Any hypothetical means of travel that exceeds the speed of light — a staple enabling technology of interstellar science fiction.", "img": ""},
  {"term": "Fauna", "slug": "fauna", "cat": "environment", "def": "The animal life of a particular region or period.", "img": ""},
  {"term": "Flying Corridors", "slug": "flying-corridors", "cat": "material", "def": "Elevated, often enclosed walkways that connect buildings above street or ground level.", "img": ""},
  {"term": "Foundry", "slug": "foundry", "cat": "industry", "def": "A workshop or plant where metal is cast — historically a source of dramatic heat, light, and machinery for a scene.", "img": ""},
  {"term": "Frank Lloyd Wright", "slug": "frank-lloyd-wright", "cat": "architect", "def": "American architect (1867–1959) and pioneer of organic architecture that integrates buildings with their landscape — Fallingwater, the Guggenheim.", "img": ""},
  {"term": "Frei Otto", "slug": "frei-otto", "cat": "architect", "def": "German architect and engineer known for lightweight tensile and gridshell structures inspired by natural forms, notably the Munich Olympic Stadium roof.", "img": ""},
  {"term": "Funicular", "slug": "funicular", "cat": "vehicle", "def": "A cable railway on a steep incline, in which ascending and descending cars counterbalance each other.", "img": ""},
  {"term": "Fusion Reactor", "slug": "fusion-reactor", "cat": "tech", "def": "A reactor that generates power by fusing light atomic nuclei, releasing far more energy than fission for the same fuel mass.", "img": ""},
  {"term": "Gas Giant Refinery", "slug": "gas-giant-refinery", "cat": "industry", "def": "A facility that harvests and processes gases drawn directly from a gas giant's atmosphere.", "img": ""},
  {"term": "Gate", "slug": "gate", "cat": "building", "def": "A controlled opening in a wall, fence, or perimeter — the architectural threshold between inside and outside.", "img": ""},
  {"term": "Geothermal", "slug": "geothermal", "cat": "industry", "def": "Energy or heat drawn from the earth's internal temperature.", "img": ""},
  {"term": "Gravitas", "slug": "gravitas", "cat": "scene", "def": "A quality of weight, seriousness, and dignity a scene or structure is meant to project.", "img": ""},
  {"term": "Gravity Cycle", "slug": "gravity-cycle", "cat": "tech", "def": "A recurring pattern of changing gravitational force, whether natural or engineered.", "img": ""},
  {"term": "Guardians", "slug": "guardians", "cat": "scene", "def": "Figures or constructs whose purpose is to protect or watch over a place.", "img": ""},
  {"term": "Gunship", "slug": "gunship", "cat": "vehicle", "def": "An armed vehicle or aircraft built primarily to deliver firepower in support of ground operations.", "img": ""},
  {"term": "Hab Module", "slug": "hab-module", "cat": "vehicle", "def": "A prefabricated living module for a spacecraft or station, typically one of several docked or connected units.", "img": ""},
  {"term": "Habitat", "slug": "habitat", "cat": "mega", "def": "A generic term for any engineered environment built to sustain life away from a planet's natural surface conditions.", "img": ""},
  {"term": "Hanging Banners", "slug": "hanging-banners", "cat": "material", "def": "Large vertical fabric or material panels suspended within a space, used to add scale, color, or wayfinding.", "img": ""},
  {"term": "Harvester", "slug": "harvester", "cat": "industry", "def": "A machine or vehicle built to gather a resource — crops, minerals, or energy — at scale.", "img": ""},
  {"term": "Host Connection", "slug": "host-connection", "cat": "tech", "def": "A data or physical link that connects a device or person into a larger network or system.", "img": ""},
  {"term": "Hover Racer", "slug": "hover-racer", "cat": "vehicle", "def": "A high-speed vehicle that rides on a cushion of air or a magnetic field rather than wheels.", "img": ""},
  {"term": "Hyperspace", "slug": "hyperspace", "cat": "tech", "def": "A hypothetical higher-dimensional shortcut through normal space, used narratively to make interstellar travel practical.", "img": ""},
  {"term": "Impenetrable", "slug": "impenetrable", "cat": "scene", "def": "A descriptor for a barrier or defense that cannot be breached.", "img": ""},
  {"term": "Interstellar Highway", "slug": "interstellar-highway", "cat": "mega", "def": "A conceptual transit corridor engineered through space to make interstellar travel faster or more efficient, e.g. via chained wormholes or gravity assists.", "img": ""},
  {"term": "Interstitial Space", "slug": "interstitial-space", "cat": "environment", "def": "A space that exists between a structure's more clearly defined or intended volumes.", "img": ""},
  {"term": "Island", "slug": "island", "cat": "environment", "def": "A body of land completely surrounded by water.", "img": ""},
  {"term": "K9 Robot", "slug": "k9-robot", "cat": "tech", "def": "A dog-shaped robotic companion or unit.", "img": ""},
  {"term": "Kinetic sculptures", "slug": "kinetic-sculptures", "cat": "material", "def": "Sculptural works with moving parts, powered by motors, wind, or people, that change form over time.", "img": ""},
  {"term": "Landing Platform", "slug": "landing-platform", "cat": "building", "def": "A dedicated surface built for aircraft, spacecraft, or vehicles to arrive and depart.", "img": ""},
  {"term": "Lapendary Acoustic Panels", "slug": "lapendary-acoustic-panels", "cat": "material", "def": "Sound-dampening wall panels detailed with a hard, faceted, gem-cut surface treatment.", "img": ""},
  {"term": "Loader/Loading", "slug": "loader-loading", "cat": "vehicle", "def": "Equipment or the process used to move cargo onto or off of a vehicle, craft, or facility.", "img": ""},
  {"term": "Lobby of a mega-corporation's tower", "slug": "lobby-of-a-mega-corporation-s-tower", "cat": "scene", "def": "A staged compositional prompt: the imposing, status-signaling ground-floor entrance hall of a corporate skyscraper.", "img": ""},
  {"term": "Louis Kahn", "slug": "louis-kahn", "cat": "architect", "def": "American architect (1901–1974) known for monumental, light-driven concrete and brick buildings — the Salk Institute, Bangladesh's National Assembly Building.", "img": ""},
  {"term": "Main Concourse", "slug": "main-concourse", "cat": "building", "def": "A building's principal circulation hall — the central space that organizes movement to everything else.", "img": ""},
  {"term": "Mangrove", "slug": "mangrove", "cat": "environment", "def": "A dense coastal forest of salt-tolerant trees, rooted in tidal shallows.", "img": ""},
  {"term": "Matrioshka Brain", "slug": "matrioshka-brain", "cat": "mega", "def": "A theoretical megastructure of nested Dyson spheres, each shell using the waste heat of the one inside it to power a civilization-scale computer.", "img": ""},
  {"term": "Mecho Shade Systems", "slug": "mecho-shade-systems", "cat": "material", "def": "Motorized shading systems — louvers, screens, or blinds — that mechanically adjust to control light and heat.", "img": ""},
  {"term": "Mecho Shades", "slug": "mecho-shades", "cat": "material", "def": "See Mecho Shade Systems — motorized, mechanically adjustable shading elements.", "img": ""},
  {"term": "Med Kit", "slug": "med-kit", "cat": "tech", "def": "A portable kit of supplies for treating injuries in the field.", "img": ""},
  {"term": "Medical Pen", "slug": "medical-pen", "cat": "tech", "def": "A compact device designed to administer medication or treatment quickly.", "img": ""},
  {"term": "Merchants", "slug": "merchants", "cat": "scene", "def": "Figures engaged in trade, often used to populate and animate a marketplace scene.", "img": ""},
  {"term": "Mesozoic Period", "slug": "mesozoic-period", "cat": "creature", "def": "The roughly 186-million-year span, from about 252 to 66 million years ago, known as the age of dinosaurs.", "img": ""},
  {"term": "Mining Quarry", "slug": "mining-quarry", "cat": "industry", "def": "An open excavation from which stone, ore, or minerals are extracted.", "img": ""},
  {"term": "Mobile Power Reactor", "slug": "mobile-power-reactor", "cat": "tech", "def": "A power-generation unit engineered to be transported and operated away from fixed infrastructure.", "img": ""},
  {"term": "Monolithic Architecture", "slug": "monolithic-architecture", "cat": "style", "def": "A building conceived and read as a single continuous mass rather than an assembly of distinct parts.", "img": ""},
  {"term": "Monorail", "slug": "monorail", "cat": "vehicle", "def": "A railway whose vehicles run on or are suspended from a single rail, often chosen for its light structural footprint.", "img": ""},
  {"term": "Movable City", "slug": "movable-city", "cat": "mega", "def": "A city built on a mobile chassis — legs, treads, or a hull — that relocates as a whole, often in response to resource depletion.", "img": ""},
  {"term": "Observatory", "slug": "observatory", "cat": "building", "def": "A structure built to house instruments for observing astronomical, meteorological, or other distant phenomena.", "img": ""},
  {"term": "Orbital Construction", "slug": "orbital-construction", "cat": "industry", "def": "The assembly of structures or vessels directly in orbit rather than on a planetary surface.", "img": ""},
  {"term": "Orbital Ring", "slug": "orbital-ring", "cat": "mega", "def": "A structure encircling a planet at orbital velocity, tethered to the surface by cables — a space-elevator alternative for cheap access to orbit.", "img": ""},
  {"term": "Orbital Shipyard", "slug": "orbital-shipyard", "cat": "industry", "def": "A facility in orbit dedicated to building or repairing spacecraft.", "img": ""},
  {"term": "Ornithischian", "slug": "ornithischian", "cat": "creature", "def": "One of the two major dinosaur orders, defined by a backward-pointing, bird-like hip structure — despite being unrelated to birds.", "img": ""},
  {"term": "Outpost", "slug": "outpost", "cat": "building", "def": "A small, remote settlement or station established ahead of, or independent from, a larger base of operations.", "img": ""},
  {"term": "Overbuild", "slug": "overbuild", "cat": "material", "def": "Construction added above or beyond an existing structure's original scope, often exploiting unused air rights or capacity.", "img": ""},
  {"term": "Paolo Soleri", "slug": "paolo-soleri", "cat": "architect", "def": "Italian-American architect who coined \"arcology\" and built Arcosanti in Arizona as an experimental prototype of a dense, self-contained city.", "img": ""},
  {"term": "Parade", "slug": "parade", "cat": "scene", "def": "A procession moving through a space, used to stage scale, crowd, and spectacle.", "img": ""},
  {"term": "Plasma Gun", "slug": "plasma-gun", "cat": "tech", "def": "A weapon that fires a bolt or stream of superheated, ionized gas.", "img": ""},
  {"term": "Plaza", "slug": "plaza", "cat": "building", "def": "An open public square framed by surrounding buildings, used for gathering, markets, or transit.", "img": ""},
  {"term": "Polyhedral Habitat", "slug": "polyhedral-habitat", "cat": "mega", "def": "A space habitat built from a faceted, multi-sided geometric hull rather than a sphere or cylinder, often for structural efficiency.", "img": ""},
  {"term": "Portable Command Center", "slug": "portable-command-center", "cat": "building", "def": "A mobile, self-contained structure equipped to coordinate an operation from a temporary or shifting location.", "img": ""},
  {"term": "Portcullis", "slug": "portcullis", "cat": "material", "def": "A heavy, vertically-sliding gate — historically part of a fortification — lowered to seal an entrance.", "img": ""},
  {"term": "Power Cell", "slug": "power-cell", "cat": "tech", "def": "A compact, self-contained unit that stores and delivers electrical energy.", "img": ""},
  {"term": "Power Generation", "slug": "power-generation", "cat": "industry", "def": "The broad process or infrastructure of producing usable electrical energy.", "img": ""},
  {"term": "Public Lounge", "slug": "public-lounge", "cat": "building", "def": "A shared social space designed for informal gathering, distinct from more functional or transitional areas.", "img": ""},
  {"term": "Radar", "slug": "radar", "cat": "tech", "def": "A system that detects the position and movement of objects using reflected radio waves.", "img": ""},
  {"term": "Reactor", "slug": "reactor", "cat": "tech", "def": "A vessel or facility that sustains a controlled nuclear or chemical reaction to produce energy.", "img": ""},
  {"term": "Reconnaissance Aircraft", "slug": "reconnaissance-aircraft", "cat": "vehicle", "def": "An aircraft equipped to observe and gather information over a target area rather than engage it directly.", "img": ""},
  {"term": "Reconnaissance Tower", "slug": "reconnaissance-tower", "cat": "building", "def": "An elevated structure built to provide a vantage point for surveillance over surrounding terrain.", "img": ""},
  {"term": "Refinery", "slug": "refinery", "cat": "industry", "def": "A facility that processes a raw resource — oil, ore, or gas — into a usable form.", "img": ""},
  {"term": "Refueling Station", "slug": "refueling-station", "cat": "industry", "def": "A facility where vehicles or craft replenish fuel or energy.", "img": ""},
  {"term": "Repair", "slug": "repair", "cat": "scene", "def": "A compositional focus on maintenance or fixing in progress.", "img": ""},
  {"term": "Research Lab", "slug": "research-lab", "cat": "building", "def": "A building equipped for controlled scientific experimentation.", "img": ""},
  {"term": "Research Station", "slug": "research-station", "cat": "building", "def": "A remote or specialized outpost built to support ongoing scientific study, often in an extreme environment.", "img": ""},
  {"term": "Retractable", "slug": "retractable", "cat": "material", "def": "A descriptor for any structural or surface element engineered to withdraw or fold away when not in use.", "img": ""},
  {"term": "Revolver", "slug": "revolver", "cat": "tech", "def": "A repeating handgun that rotates a cylinder of chambered rounds into firing position.", "img": ""},
  {"term": "Ribbon Board", "slug": "ribbon-board", "cat": "material", "def": "A continuous strip of digital signage or lighting wrapped along a structure or arena.", "img": ""},
  {"term": "Rigging Grid", "slug": "rigging-grid", "cat": "material", "def": "An overhead lattice used to mount, hoist, and route lighting, scenery, or equipment.", "img": ""},
  {"term": "RingWorld", "slug": "ringworld", "cat": "mega", "def": "A megastructure concept (Larry Niven): a rigid ring encircling a star at roughly the radius of a planetary orbit, with habitable surface area millions of times that of a planet.", "img": ""},
  {"term": "Rungworld", "slug": "rungworld", "cat": "mega", "def": "A variant spelling of Ringworld appearing in this collection — see RingWorld.", "img": ""},
  {"term": "Salt Mining", "slug": "salt-mining", "cat": "industry", "def": "The extraction of salt from underground deposits or evaporated brine.", "img": ""},
  {"term": "Salvaging", "slug": "salvaging", "cat": "industry", "def": "The recovery of usable materials or equipment from wrecked or discarded structures.", "img": ""},
  {"term": "Satellite", "slug": "satellite", "cat": "tech", "def": "An object placed in orbit around a planet or other body, natural or artificial.", "img": ""},
  {"term": "Sauropodomorph", "slug": "sauropodomorph", "cat": "creature", "def": "The dinosaur lineage that includes the giant long-necked sauropods and their smaller early ancestors.", "img": ""},
  {"term": "Sauropods", "slug": "sauropods", "cat": "creature", "def": "Massive, long-necked, long-tailed herbivorous dinosaurs — among the largest land animals ever to exist.", "img": ""},
  {"term": "Scanner", "slug": "scanner", "cat": "tech", "def": "A device that examines an object, area, or person to extract data about it.", "img": ""},
  {"term": "Scanning gates", "slug": "scanning-gates", "cat": "material", "def": "A checkpoint fixture that screens people or vehicles for security as they pass through.", "img": ""},
  {"term": "Sculpture", "slug": "sculpture", "cat": "material", "def": "A three-dimensional artwork used within a space as a focal or scale-giving element.", "img": ""},
  {"term": "Seastead", "slug": "seastead", "cat": "mega", "def": "A permanent settlement built to float on or anchor within the open ocean, independent of any nation's land territory.", "img": ""},
  {"term": "Sector", "slug": "sector", "cat": "building", "def": "A designated zone or district within a larger settlement or facility, usually defined by function or jurisdiction.", "img": ""},
  {"term": "Security Dock", "slug": "security-dock", "cat": "building", "def": "A docking facility built with added defensive or screening infrastructure.", "img": ""},
  {"term": "Semiotics", "slug": "semiotics", "cat": "style", "def": "The study of signs and symbols — in architecture, the meaning a building's form communicates beyond its function.", "img": ""},
  {"term": "Shell World", "slug": "shell-world", "cat": "mega", "def": "A planet or moon enclosed within an artificial shell, engineered to hold an atmosphere and gravity independent of the body's natural conditions.", "img": ""},
  {"term": "Shipbreaking", "slug": "shipbreaking", "cat": "industry", "def": "The dismantling of decommissioned ships for scrap and reusable parts.", "img": ""},
  {"term": "Shop", "slug": "shop", "cat": "building", "def": "A small commercial space for retail or trade.", "img": ""},
  {"term": "Sinosauropteryx", "slug": "sinosauropteryx", "cat": "creature", "def": "The first non-avian dinosaur found with direct fossil evidence of feathers.", "img": ""},
  {"term": "Skim Coat", "slug": "skim-coat", "cat": "material", "def": "A thin finishing layer of plaster or compound applied to smooth a surface before finishing.", "img": ""},
  {"term": "Soffit", "slug": "soffit", "cat": "material", "def": "The underside of an architectural element — an eave, arch, or beam — often used as a surface for concealed lighting or ventilation.", "img": ""},
  {"term": "Space Baroque", "slug": "space-baroque", "cat": "style", "def": "An ornate, maximalist visual style applied to spacecraft or space architecture — dense surface detail and dramatic silhouettes over pure function.", "img": ""},
  {"term": "Space Farm", "slug": "space-farm", "cat": "industry", "def": "An agricultural facility built to grow food in orbit or on another world.", "img": ""},
  {"term": "Spaceport", "slug": "spaceport", "cat": "building", "def": "A facility built for launching and receiving spacecraft.", "img": ""},
  {"term": "Speeder Bike", "slug": "speeder-bike", "cat": "vehicle", "def": "A single-rider hovering or high-speed vehicle, typically light and maneuverable.", "img": ""},
  {"term": "Spiky", "slug": "spiky", "cat": "scene", "def": "A descriptor for silhouettes or surfaces built from sharp, radiating, or jagged projecting forms.", "img": ""},
  {"term": "Starship", "slug": "starship", "cat": "vehicle", "def": "A vessel built for travel between star systems.", "img": ""},
  {"term": "Storage Facility", "slug": "storage-facility", "cat": "building", "def": "A structure built primarily to hold goods, materials, or equipment.", "img": ""},
  {"term": "Surveying Device", "slug": "surveying-device", "cat": "tech", "def": "An instrument used to measure and map terrain or structures.", "img": ""},
  {"term": "Syd Mead", "slug": "syd-mead", "cat": "architect", "def": "American concept artist and self-described \"visual futurist\" whose designs for Blade Runner, Tron, and Aliens defined much of modern science-fiction production design.", "img": ""},
  {"term": "Teahouse", "slug": "teahouse", "cat": "building", "def": "A small structure dedicated to the ritual or social act of serving tea, often a study in restraint and framed views.", "img": ""},
  {"term": "Temple", "slug": "temple", "cat": "building", "def": "A structure built for worship or ritual — typically the most symbolically weighted building in its setting.", "img": ""},
  {"term": "Terrace", "slug": "terrace", "cat": "building", "def": "A raised, level outdoor platform attached to a building, often stepped into a slope.", "img": ""},
  {"term": "Terraforming", "slug": "terraforming", "cat": "tech", "def": "The hypothetical process of altering a planet's atmosphere, temperature, or surface to make it habitable.", "img": ""},
  {"term": "Thermal Blanket", "slug": "thermal-blanket", "cat": "material", "def": "An insulating covering used to regulate temperature, from a spacecraft's reflective wrap to a survival blanket.", "img": ""},
  {"term": "Theropods", "slug": "theropods", "cat": "creature", "def": "The dinosaur group of mostly bipedal, largely carnivorous species, including everything from Compsognathus to Tyrannosaurus to modern birds.", "img": ""},
  {"term": "Topopolis", "slug": "topopolis", "cat": "mega", "def": "A megastructure concept: a spin habitat built as an immensely long rotating tube, looped around a star system for habitable area comparable to a ringworld using far less material.", "img": ""},
  {"term": "Transparent Floor Panels reveal Conduits", "slug": "transparent-floor-panels-reveal-conduits", "cat": "material", "def": "Floor sections glazed or left open so a building's mechanical, structural, or utility systems are visible underfoot.", "img": ""},
  {"term": "Trellis", "slug": "trellis", "cat": "material", "def": "An open lattice structure that supports climbing plants or filters light, blurring the line between structure and landscape.", "img": ""},
  {"term": "Troodon", "slug": "troodon", "cat": "creature", "def": "A small, unusually large-brained theropod dinosaur, considered among the most intelligent dinosaurs known.", "img": ""},
  {"term": "Tropical", "slug": "tropical", "cat": "environment", "def": "A descriptor for the hot, humid climate zone near the equator.", "img": ""},
  {"term": "Tug Ship", "slug": "tug-ship", "cat": "vehicle", "def": "A small, powerful craft used to tow or reposition larger vessels or structures.", "img": ""},
  {"term": "Underground Cavern", "slug": "underground-cavern", "cat": "environment", "def": "A naturally or artificially hollowed space beneath the surface.", "img": ""},
  {"term": "Undersea Habitat - Prefab", "slug": "undersea-habitat-prefab", "cat": "mega", "def": "A modular, factory-built living or research structure designed to be lowered and sealed onto the seafloor or suspended underwater.", "img": ""},
  {"term": "Variable Air Volume (VAV)", "slug": "variable-air-volume-vav", "cat": "material", "def": "An HVAC system that adjusts the volume of conditioned air delivered to a space rather than its temperature, for more precise climate control.", "img": ""},
  {"term": "Vault", "slug": "vault", "cat": "building", "def": "A secured, enclosed space built to protect valuable or dangerous contents.", "img": ""},
  {"term": "Velociraptor Mongoliensis", "slug": "velociraptor-mongoliensis", "cat": "creature", "def": "A small, feathered theropod dinosaur from the Late Cretaceous of Mongolia, far smaller in life than its popular depiction.", "img": ""},
  {"term": "Vessel", "slug": "vessel", "cat": "vehicle", "def": "A general term for a craft built to carry people or cargo through space, sea, or air.", "img": ""},
  {"term": "Virtual/Geospatial Perimeter Fence", "slug": "virtual-geospatial-perimeter-fence", "cat": "tech", "def": "A software-defined boundary that triggers a response — alert, lockout, or tracking — when crossed, with no physical barrier required.", "img": ""},
  {"term": "Warp Drive", "slug": "warp-drive", "cat": "tech", "def": "A propulsion concept that moves a craft by distorting the space around it rather than moving through space directly.", "img": ""},
  {"term": "Warp Gate", "slug": "warp-gate", "cat": "tech", "def": "A fixed structure that opens a shortcut — a wormhole or similar passage — between two distant points.", "img": ""},
  {"term": "Water Reserves", "slug": "water-reserves", "cat": "industry", "def": "Stored supplies of water held for future or emergency use.", "img": ""},
  {"term": "Water Softener", "slug": "water-softener", "cat": "material", "def": "Equipment that removes hardness-causing minerals from water before it enters a building's plumbing.", "img": ""},
  {"term": "Waterless Planet", "slug": "waterless-planet", "cat": "environment", "def": "A world with a dry, arid geology — a stark visual counterpoint for habitats and infrastructure that must import or synthesize water.", "img": ""},
  {"term": "Worldhouse", "slug": "worldhouse", "cat": "mega", "def": "A structure that encloses and climate-controls an entire settlement or biome under a single roof or dome.", "img": ""},
];
